// Code generated by ogen, DO NOT EDIT.

package ogencl

import (
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

// Сумма платежа. Иногда партнеры ЮKassa берут с
// пользователя дополнительную комиссию, которая не
// входит в эту сумму.
// Ref: #/components/schemas/Amount
type Amount struct {
	// Трехбуквенный код валюты в формате ISO-4217. Пример: RUB.
	// Должен соответствовать валюте субаккаунта (recipient.
	// gateway_id), если вы разделяете потоки платежей, и валюте
	// аккаунта (shopId в личном кабинете), если не разделяете.
	Currency AmountCurrency `json:"currency"`
	// Сумма в выбранной валюте. Всегда дробное значение.
	// Разделитель дробной части — точка, разделитель тысяч
	// отсутствует. Количество знаков после точки зависит
	// от выбранной валюты. Пример: 1000.00.
	Value string `json:"value"`
}

// GetCurrency returns the value of Currency.
func (s *Amount) GetCurrency() AmountCurrency {
	return s.Currency
}

// GetValue returns the value of Value.
func (s *Amount) GetValue() string {
	return s.Value
}

// SetCurrency sets the value of Currency.
func (s *Amount) SetCurrency(val AmountCurrency) {
	s.Currency = val
}

// SetValue sets the value of Value.
func (s *Amount) SetValue(val string) {
	s.Value = val
}

// Трехбуквенный код валюты в формате ISO-4217. Пример: RUB.
// Должен соответствовать валюте субаккаунта (recipient.
// gateway_id), если вы разделяете потоки платежей, и валюте
// аккаунта (shopId в личном кабинете), если не разделяете.
type AmountCurrency string

const (
	AmountCurrencyRUB AmountCurrency = "RUB"
)

// AllValues returns all AmountCurrency values.
func (AmountCurrency) AllValues() []AmountCurrency {
	return []AmountCurrency{
		AmountCurrencyRUB,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AmountCurrency) MarshalText() ([]byte, error) {
	switch s {
	case AmountCurrencyRUB:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AmountCurrency) UnmarshalText(data []byte) error {
	switch AmountCurrency(data) {
	case AmountCurrencyRUB:
		*s = AmountCurrencyRUB
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type BasicAuth struct {
	Username string
	Password string
}

// GetUsername returns the value of Username.
func (s *BasicAuth) GetUsername() string {
	return s.Username
}

// GetPassword returns the value of Password.
func (s *BasicAuth) GetPassword() string {
	return s.Password
}

// SetUsername sets the value of Username.
func (s *BasicAuth) SetUsername(val string) {
	s.Username = val
}

// SetPassword sets the value of Password.
func (s *BasicAuth) SetPassword(val string) {
	s.Password = val
}

// Ref: #/components/schemas/Metadata
type Metadata map[string]jx.Raw

func (s *Metadata) init() Metadata {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptMetadata returns new OptMetadata with value set to v.
func NewOptMetadata(v Metadata) OptMetadata {
	return OptMetadata{
		Value: v,
		Set:   true,
	}
}

// OptMetadata is optional Metadata.
type OptMetadata struct {
	Value Metadata
	Set   bool
}

// IsSet returns true if OptMetadata was set.
func (o OptMetadata) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptMetadata) Reset() {
	var v Metadata
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptMetadata) SetTo(v Metadata) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptMetadata) Get() (v Metadata, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptMetadata) Or(d Metadata) Metadata {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentAuthorizationDetails returns new OptPaymentAuthorizationDetails with value set to v.
func NewOptPaymentAuthorizationDetails(v PaymentAuthorizationDetails) OptPaymentAuthorizationDetails {
	return OptPaymentAuthorizationDetails{
		Value: v,
		Set:   true,
	}
}

// OptPaymentAuthorizationDetails is optional PaymentAuthorizationDetails.
type OptPaymentAuthorizationDetails struct {
	Value PaymentAuthorizationDetails
	Set   bool
}

// IsSet returns true if OptPaymentAuthorizationDetails was set.
func (o OptPaymentAuthorizationDetails) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentAuthorizationDetails) Reset() {
	var v PaymentAuthorizationDetails
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentAuthorizationDetails) SetTo(v PaymentAuthorizationDetails) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentAuthorizationDetails) Get() (v PaymentAuthorizationDetails, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentAuthorizationDetails) Or(d PaymentAuthorizationDetails) PaymentAuthorizationDetails {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentAuthorizationDetailsThreeDSecure returns new OptPaymentAuthorizationDetailsThreeDSecure with value set to v.
func NewOptPaymentAuthorizationDetailsThreeDSecure(v PaymentAuthorizationDetailsThreeDSecure) OptPaymentAuthorizationDetailsThreeDSecure {
	return OptPaymentAuthorizationDetailsThreeDSecure{
		Value: v,
		Set:   true,
	}
}

// OptPaymentAuthorizationDetailsThreeDSecure is optional PaymentAuthorizationDetailsThreeDSecure.
type OptPaymentAuthorizationDetailsThreeDSecure struct {
	Value PaymentAuthorizationDetailsThreeDSecure
	Set   bool
}

// IsSet returns true if OptPaymentAuthorizationDetailsThreeDSecure was set.
func (o OptPaymentAuthorizationDetailsThreeDSecure) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentAuthorizationDetailsThreeDSecure) Reset() {
	var v PaymentAuthorizationDetailsThreeDSecure
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentAuthorizationDetailsThreeDSecure) SetTo(v PaymentAuthorizationDetailsThreeDSecure) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentAuthorizationDetailsThreeDSecure) Get() (v PaymentAuthorizationDetailsThreeDSecure, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentAuthorizationDetailsThreeDSecure) Or(d PaymentAuthorizationDetailsThreeDSecure) PaymentAuthorizationDetailsThreeDSecure {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentConfirmation returns new OptPaymentConfirmation with value set to v.
func NewOptPaymentConfirmation(v PaymentConfirmation) OptPaymentConfirmation {
	return OptPaymentConfirmation{
		Value: v,
		Set:   true,
	}
}

// OptPaymentConfirmation is optional PaymentConfirmation.
type OptPaymentConfirmation struct {
	Value PaymentConfirmation
	Set   bool
}

// IsSet returns true if OptPaymentConfirmation was set.
func (o OptPaymentConfirmation) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentConfirmation) Reset() {
	var v PaymentConfirmation
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentConfirmation) SetTo(v PaymentConfirmation) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentConfirmation) Get() (v PaymentConfirmation, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentConfirmation) Or(d PaymentConfirmation) PaymentConfirmation {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentIncomeAmount returns new OptPaymentIncomeAmount with value set to v.
func NewOptPaymentIncomeAmount(v PaymentIncomeAmount) OptPaymentIncomeAmount {
	return OptPaymentIncomeAmount{
		Value: v,
		Set:   true,
	}
}

// OptPaymentIncomeAmount is optional PaymentIncomeAmount.
type OptPaymentIncomeAmount struct {
	Value PaymentIncomeAmount
	Set   bool
}

// IsSet returns true if OptPaymentIncomeAmount was set.
func (o OptPaymentIncomeAmount) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentIncomeAmount) Reset() {
	var v PaymentIncomeAmount
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentIncomeAmount) SetTo(v PaymentIncomeAmount) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentIncomeAmount) Get() (v PaymentIncomeAmount, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentIncomeAmount) Or(d PaymentIncomeAmount) PaymentIncomeAmount {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentPaymentMethod returns new OptPaymentPaymentMethod with value set to v.
func NewOptPaymentPaymentMethod(v PaymentPaymentMethod) OptPaymentPaymentMethod {
	return OptPaymentPaymentMethod{
		Value: v,
		Set:   true,
	}
}

// OptPaymentPaymentMethod is optional PaymentPaymentMethod.
type OptPaymentPaymentMethod struct {
	Value PaymentPaymentMethod
	Set   bool
}

// IsSet returns true if OptPaymentPaymentMethod was set.
func (o OptPaymentPaymentMethod) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentPaymentMethod) Reset() {
	var v PaymentPaymentMethod
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentPaymentMethod) SetTo(v PaymentPaymentMethod) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentPaymentMethod) Get() (v PaymentPaymentMethod, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentPaymentMethod) Or(d PaymentPaymentMethod) PaymentPaymentMethod {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentPaymentMethodCard returns new OptPaymentPaymentMethodCard with value set to v.
func NewOptPaymentPaymentMethodCard(v PaymentPaymentMethodCard) OptPaymentPaymentMethodCard {
	return OptPaymentPaymentMethodCard{
		Value: v,
		Set:   true,
	}
}

// OptPaymentPaymentMethodCard is optional PaymentPaymentMethodCard.
type OptPaymentPaymentMethodCard struct {
	Value PaymentPaymentMethodCard
	Set   bool
}

// IsSet returns true if OptPaymentPaymentMethodCard was set.
func (o OptPaymentPaymentMethodCard) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentPaymentMethodCard) Reset() {
	var v PaymentPaymentMethodCard
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentPaymentMethodCard) SetTo(v PaymentPaymentMethodCard) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentPaymentMethodCard) Get() (v PaymentPaymentMethodCard, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentPaymentMethodCard) Or(d PaymentPaymentMethodCard) PaymentPaymentMethodCard {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentPaymentMethodCardCardProduct returns new OptPaymentPaymentMethodCardCardProduct with value set to v.
func NewOptPaymentPaymentMethodCardCardProduct(v PaymentPaymentMethodCardCardProduct) OptPaymentPaymentMethodCardCardProduct {
	return OptPaymentPaymentMethodCardCardProduct{
		Value: v,
		Set:   true,
	}
}

// OptPaymentPaymentMethodCardCardProduct is optional PaymentPaymentMethodCardCardProduct.
type OptPaymentPaymentMethodCardCardProduct struct {
	Value PaymentPaymentMethodCardCardProduct
	Set   bool
}

// IsSet returns true if OptPaymentPaymentMethodCardCardProduct was set.
func (o OptPaymentPaymentMethodCardCardProduct) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentPaymentMethodCardCardProduct) Reset() {
	var v PaymentPaymentMethodCardCardProduct
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentPaymentMethodCardCardProduct) SetTo(v PaymentPaymentMethodCardCardProduct) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentPaymentMethodCardCardProduct) Get() (v PaymentPaymentMethodCardCardProduct, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentPaymentMethodCardCardProduct) Or(d PaymentPaymentMethodCardCardProduct) PaymentPaymentMethodCardCardProduct {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptReqPaymentConfirmation returns new OptReqPaymentConfirmation with value set to v.
func NewOptReqPaymentConfirmation(v ReqPaymentConfirmation) OptReqPaymentConfirmation {
	return OptReqPaymentConfirmation{
		Value: v,
		Set:   true,
	}
}

// OptReqPaymentConfirmation is optional ReqPaymentConfirmation.
type OptReqPaymentConfirmation struct {
	Value ReqPaymentConfirmation
	Set   bool
}

// IsSet returns true if OptReqPaymentConfirmation was set.
func (o OptReqPaymentConfirmation) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptReqPaymentConfirmation) Reset() {
	var v ReqPaymentConfirmation
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptReqPaymentConfirmation) SetTo(v ReqPaymentConfirmation) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptReqPaymentConfirmation) Get() (v ReqPaymentConfirmation, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptReqPaymentConfirmation) Or(d ReqPaymentConfirmation) ReqPaymentConfirmation {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Payment
type Payment struct {
	ID                   string                         `json:"id"`
	Status               PaymentStatus                  `json:"status"`
	Paid                 bool                           `json:"paid"`
	Amount               Amount                         `json:"amount"`
	AuthorizationDetails OptPaymentAuthorizationDetails `json:"authorization_details"`
	CreatedAt            time.Time                      `json:"created_at"`
	Description          OptString                      `json:"description"`
	ExpiresAt            OptDateTime                    `json:"expires_at"`
	Metadata             OptMetadata                    `json:"metadata"`
	PaymentMethod        OptPaymentPaymentMethod        `json:"payment_method"`
	Recipient            PaymentRecipient               `json:"recipient"`
	Refundable           bool                           `json:"refundable"`
	Test                 bool                           `json:"test"`
	IncomeAmount         OptPaymentIncomeAmount         `json:"income_amount"`
	Confirmation         OptPaymentConfirmation         `json:"confirmation"`
}

// GetID returns the value of ID.
func (s *Payment) GetID() string {
	return s.ID
}

// GetStatus returns the value of Status.
func (s *Payment) GetStatus() PaymentStatus {
	return s.Status
}

// GetPaid returns the value of Paid.
func (s *Payment) GetPaid() bool {
	return s.Paid
}

// GetAmount returns the value of Amount.
func (s *Payment) GetAmount() Amount {
	return s.Amount
}

// GetAuthorizationDetails returns the value of AuthorizationDetails.
func (s *Payment) GetAuthorizationDetails() OptPaymentAuthorizationDetails {
	return s.AuthorizationDetails
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Payment) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetDescription returns the value of Description.
func (s *Payment) GetDescription() OptString {
	return s.Description
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *Payment) GetExpiresAt() OptDateTime {
	return s.ExpiresAt
}

// GetMetadata returns the value of Metadata.
func (s *Payment) GetMetadata() OptMetadata {
	return s.Metadata
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *Payment) GetPaymentMethod() OptPaymentPaymentMethod {
	return s.PaymentMethod
}

// GetRecipient returns the value of Recipient.
func (s *Payment) GetRecipient() PaymentRecipient {
	return s.Recipient
}

// GetRefundable returns the value of Refundable.
func (s *Payment) GetRefundable() bool {
	return s.Refundable
}

// GetTest returns the value of Test.
func (s *Payment) GetTest() bool {
	return s.Test
}

// GetIncomeAmount returns the value of IncomeAmount.
func (s *Payment) GetIncomeAmount() OptPaymentIncomeAmount {
	return s.IncomeAmount
}

// GetConfirmation returns the value of Confirmation.
func (s *Payment) GetConfirmation() OptPaymentConfirmation {
	return s.Confirmation
}

// SetID sets the value of ID.
func (s *Payment) SetID(val string) {
	s.ID = val
}

// SetStatus sets the value of Status.
func (s *Payment) SetStatus(val PaymentStatus) {
	s.Status = val
}

// SetPaid sets the value of Paid.
func (s *Payment) SetPaid(val bool) {
	s.Paid = val
}

// SetAmount sets the value of Amount.
func (s *Payment) SetAmount(val Amount) {
	s.Amount = val
}

// SetAuthorizationDetails sets the value of AuthorizationDetails.
func (s *Payment) SetAuthorizationDetails(val OptPaymentAuthorizationDetails) {
	s.AuthorizationDetails = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Payment) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetDescription sets the value of Description.
func (s *Payment) SetDescription(val OptString) {
	s.Description = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *Payment) SetExpiresAt(val OptDateTime) {
	s.ExpiresAt = val
}

// SetMetadata sets the value of Metadata.
func (s *Payment) SetMetadata(val OptMetadata) {
	s.Metadata = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *Payment) SetPaymentMethod(val OptPaymentPaymentMethod) {
	s.PaymentMethod = val
}

// SetRecipient sets the value of Recipient.
func (s *Payment) SetRecipient(val PaymentRecipient) {
	s.Recipient = val
}

// SetRefundable sets the value of Refundable.
func (s *Payment) SetRefundable(val bool) {
	s.Refundable = val
}

// SetTest sets the value of Test.
func (s *Payment) SetTest(val bool) {
	s.Test = val
}

// SetIncomeAmount sets the value of IncomeAmount.
func (s *Payment) SetIncomeAmount(val OptPaymentIncomeAmount) {
	s.IncomeAmount = val
}

// SetConfirmation sets the value of Confirmation.
func (s *Payment) SetConfirmation(val OptPaymentConfirmation) {
	s.Confirmation = val
}

type PaymentAuthorizationDetails struct {
	Rrn          OptString                                  `json:"rrn"`
	AuthCode     OptString                                  `json:"auth_code"`
	ThreeDSecure OptPaymentAuthorizationDetailsThreeDSecure `json:"three_d_secure"`
}

// GetRrn returns the value of Rrn.
func (s *PaymentAuthorizationDetails) GetRrn() OptString {
	return s.Rrn
}

// GetAuthCode returns the value of AuthCode.
func (s *PaymentAuthorizationDetails) GetAuthCode() OptString {
	return s.AuthCode
}

// GetThreeDSecure returns the value of ThreeDSecure.
func (s *PaymentAuthorizationDetails) GetThreeDSecure() OptPaymentAuthorizationDetailsThreeDSecure {
	return s.ThreeDSecure
}

// SetRrn sets the value of Rrn.
func (s *PaymentAuthorizationDetails) SetRrn(val OptString) {
	s.Rrn = val
}

// SetAuthCode sets the value of AuthCode.
func (s *PaymentAuthorizationDetails) SetAuthCode(val OptString) {
	s.AuthCode = val
}

// SetThreeDSecure sets the value of ThreeDSecure.
func (s *PaymentAuthorizationDetails) SetThreeDSecure(val OptPaymentAuthorizationDetailsThreeDSecure) {
	s.ThreeDSecure = val
}

type PaymentAuthorizationDetailsThreeDSecure struct {
	Applied OptBool `json:"applied"`
}

// GetApplied returns the value of Applied.
func (s *PaymentAuthorizationDetailsThreeDSecure) GetApplied() OptBool {
	return s.Applied
}

// SetApplied sets the value of Applied.
func (s *PaymentAuthorizationDetailsThreeDSecure) SetApplied(val OptBool) {
	s.Applied = val
}

type PaymentConfirmation struct {
	Type              PaymentConfirmationType `json:"type"`
	ConfirmationToken OptString               `json:"confirmation_token"`
}

// GetType returns the value of Type.
func (s *PaymentConfirmation) GetType() PaymentConfirmationType {
	return s.Type
}

// GetConfirmationToken returns the value of ConfirmationToken.
func (s *PaymentConfirmation) GetConfirmationToken() OptString {
	return s.ConfirmationToken
}

// SetType sets the value of Type.
func (s *PaymentConfirmation) SetType(val PaymentConfirmationType) {
	s.Type = val
}

// SetConfirmationToken sets the value of ConfirmationToken.
func (s *PaymentConfirmation) SetConfirmationToken(val OptString) {
	s.ConfirmationToken = val
}

// Ref: #/components/schemas/PaymentConfirmationEmbedded
type PaymentConfirmationEmbedded struct {
	// Значение — embedded.
	// Код сценария подтверждения.
	Type PaymentConfirmationEmbeddedType `json:"type"`
	// Язык интерфейса, писем и смс, которые будет видеть или
	// получать пользователь. Формат соответствует ISO/IEC 15897.
	// Возможные значения: ru_RU, en_US. Регистр важен.
	Locale OptString `json:"locale"`
}

// GetType returns the value of Type.
func (s *PaymentConfirmationEmbedded) GetType() PaymentConfirmationEmbeddedType {
	return s.Type
}

// GetLocale returns the value of Locale.
func (s *PaymentConfirmationEmbedded) GetLocale() OptString {
	return s.Locale
}

// SetType sets the value of Type.
func (s *PaymentConfirmationEmbedded) SetType(val PaymentConfirmationEmbeddedType) {
	s.Type = val
}

// SetLocale sets the value of Locale.
func (s *PaymentConfirmationEmbedded) SetLocale(val OptString) {
	s.Locale = val
}

// Значение — embedded.
// Код сценария подтверждения.
type PaymentConfirmationEmbeddedType string

const (
	PaymentConfirmationEmbeddedTypeEmbedded PaymentConfirmationEmbeddedType = "embedded"
	PaymentConfirmationEmbeddedTypeExternal PaymentConfirmationEmbeddedType = "external"
)

// AllValues returns all PaymentConfirmationEmbeddedType values.
func (PaymentConfirmationEmbeddedType) AllValues() []PaymentConfirmationEmbeddedType {
	return []PaymentConfirmationEmbeddedType{
		PaymentConfirmationEmbeddedTypeEmbedded,
		PaymentConfirmationEmbeddedTypeExternal,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PaymentConfirmationEmbeddedType) MarshalText() ([]byte, error) {
	switch s {
	case PaymentConfirmationEmbeddedTypeEmbedded:
		return []byte(s), nil
	case PaymentConfirmationEmbeddedTypeExternal:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PaymentConfirmationEmbeddedType) UnmarshalText(data []byte) error {
	switch PaymentConfirmationEmbeddedType(data) {
	case PaymentConfirmationEmbeddedTypeEmbedded:
		*s = PaymentConfirmationEmbeddedTypeEmbedded
		return nil
	case PaymentConfirmationEmbeddedTypeExternal:
		*s = PaymentConfirmationEmbeddedTypeExternal
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type PaymentConfirmationType string

const (
	PaymentConfirmationTypeEmbedded PaymentConfirmationType = "embedded"
)

// AllValues returns all PaymentConfirmationType values.
func (PaymentConfirmationType) AllValues() []PaymentConfirmationType {
	return []PaymentConfirmationType{
		PaymentConfirmationTypeEmbedded,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PaymentConfirmationType) MarshalText() ([]byte, error) {
	switch s {
	case PaymentConfirmationTypeEmbedded:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PaymentConfirmationType) UnmarshalText(data []byte) error {
	switch PaymentConfirmationType(data) {
	case PaymentConfirmationTypeEmbedded:
		*s = PaymentConfirmationTypeEmbedded
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type PaymentIncomeAmount struct {
	Value    OptString `json:"value"`
	Currency OptString `json:"currency"`
}

// GetValue returns the value of Value.
func (s *PaymentIncomeAmount) GetValue() OptString {
	return s.Value
}

// GetCurrency returns the value of Currency.
func (s *PaymentIncomeAmount) GetCurrency() OptString {
	return s.Currency
}

// SetValue sets the value of Value.
func (s *PaymentIncomeAmount) SetValue(val OptString) {
	s.Value = val
}

// SetCurrency sets the value of Currency.
func (s *PaymentIncomeAmount) SetCurrency(val OptString) {
	s.Currency = val
}

type PaymentPaymentMethod struct {
	Type  string                      `json:"type"`
	ID    string                      `json:"id"`
	Saved bool                        `json:"saved"`
	Card  OptPaymentPaymentMethodCard `json:"card"`
	Title OptString                   `json:"title"`
}

// GetType returns the value of Type.
func (s *PaymentPaymentMethod) GetType() string {
	return s.Type
}

// GetID returns the value of ID.
func (s *PaymentPaymentMethod) GetID() string {
	return s.ID
}

// GetSaved returns the value of Saved.
func (s *PaymentPaymentMethod) GetSaved() bool {
	return s.Saved
}

// GetCard returns the value of Card.
func (s *PaymentPaymentMethod) GetCard() OptPaymentPaymentMethodCard {
	return s.Card
}

// GetTitle returns the value of Title.
func (s *PaymentPaymentMethod) GetTitle() OptString {
	return s.Title
}

// SetType sets the value of Type.
func (s *PaymentPaymentMethod) SetType(val string) {
	s.Type = val
}

// SetID sets the value of ID.
func (s *PaymentPaymentMethod) SetID(val string) {
	s.ID = val
}

// SetSaved sets the value of Saved.
func (s *PaymentPaymentMethod) SetSaved(val bool) {
	s.Saved = val
}

// SetCard sets the value of Card.
func (s *PaymentPaymentMethod) SetCard(val OptPaymentPaymentMethodCard) {
	s.Card = val
}

// SetTitle sets the value of Title.
func (s *PaymentPaymentMethod) SetTitle(val OptString) {
	s.Title = val
}

type PaymentPaymentMethodCard struct {
	First6        OptString                              `json:"first6"`
	Last4         OptString                              `json:"last4"`
	ExpiryMonth   OptString                              `json:"expiry_month"`
	ExpiryYear    OptString                              `json:"expiry_year"`
	CardType      OptString                              `json:"card_type"`
	CardProduct   OptPaymentPaymentMethodCardCardProduct `json:"card_product"`
	IssuerCountry OptString                              `json:"issuer_country"`
	IssuerName    OptString                              `json:"issuer_name"`
}

// GetFirst6 returns the value of First6.
func (s *PaymentPaymentMethodCard) GetFirst6() OptString {
	return s.First6
}

// GetLast4 returns the value of Last4.
func (s *PaymentPaymentMethodCard) GetLast4() OptString {
	return s.Last4
}

// GetExpiryMonth returns the value of ExpiryMonth.
func (s *PaymentPaymentMethodCard) GetExpiryMonth() OptString {
	return s.ExpiryMonth
}

// GetExpiryYear returns the value of ExpiryYear.
func (s *PaymentPaymentMethodCard) GetExpiryYear() OptString {
	return s.ExpiryYear
}

// GetCardType returns the value of CardType.
func (s *PaymentPaymentMethodCard) GetCardType() OptString {
	return s.CardType
}

// GetCardProduct returns the value of CardProduct.
func (s *PaymentPaymentMethodCard) GetCardProduct() OptPaymentPaymentMethodCardCardProduct {
	return s.CardProduct
}

// GetIssuerCountry returns the value of IssuerCountry.
func (s *PaymentPaymentMethodCard) GetIssuerCountry() OptString {
	return s.IssuerCountry
}

// GetIssuerName returns the value of IssuerName.
func (s *PaymentPaymentMethodCard) GetIssuerName() OptString {
	return s.IssuerName
}

// SetFirst6 sets the value of First6.
func (s *PaymentPaymentMethodCard) SetFirst6(val OptString) {
	s.First6 = val
}

// SetLast4 sets the value of Last4.
func (s *PaymentPaymentMethodCard) SetLast4(val OptString) {
	s.Last4 = val
}

// SetExpiryMonth sets the value of ExpiryMonth.
func (s *PaymentPaymentMethodCard) SetExpiryMonth(val OptString) {
	s.ExpiryMonth = val
}

// SetExpiryYear sets the value of ExpiryYear.
func (s *PaymentPaymentMethodCard) SetExpiryYear(val OptString) {
	s.ExpiryYear = val
}

// SetCardType sets the value of CardType.
func (s *PaymentPaymentMethodCard) SetCardType(val OptString) {
	s.CardType = val
}

// SetCardProduct sets the value of CardProduct.
func (s *PaymentPaymentMethodCard) SetCardProduct(val OptPaymentPaymentMethodCardCardProduct) {
	s.CardProduct = val
}

// SetIssuerCountry sets the value of IssuerCountry.
func (s *PaymentPaymentMethodCard) SetIssuerCountry(val OptString) {
	s.IssuerCountry = val
}

// SetIssuerName sets the value of IssuerName.
func (s *PaymentPaymentMethodCard) SetIssuerName(val OptString) {
	s.IssuerName = val
}

type PaymentPaymentMethodCardCardProduct struct {
	Code OptString `json:"code"`
	Name OptString `json:"name"`
}

// GetCode returns the value of Code.
func (s *PaymentPaymentMethodCardCardProduct) GetCode() OptString {
	return s.Code
}

// GetName returns the value of Name.
func (s *PaymentPaymentMethodCardCardProduct) GetName() OptString {
	return s.Name
}

// SetCode sets the value of Code.
func (s *PaymentPaymentMethodCardCardProduct) SetCode(val OptString) {
	s.Code = val
}

// SetName sets the value of Name.
func (s *PaymentPaymentMethodCardCardProduct) SetName(val OptString) {
	s.Name = val
}

type PaymentRecipient struct {
	AccountID OptString `json:"account_id"`
	GatewayID OptString `json:"gateway_id"`
}

// GetAccountID returns the value of AccountID.
func (s *PaymentRecipient) GetAccountID() OptString {
	return s.AccountID
}

// GetGatewayID returns the value of GatewayID.
func (s *PaymentRecipient) GetGatewayID() OptString {
	return s.GatewayID
}

// SetAccountID sets the value of AccountID.
func (s *PaymentRecipient) SetAccountID(val OptString) {
	s.AccountID = val
}

// SetGatewayID sets the value of GatewayID.
func (s *PaymentRecipient) SetGatewayID(val OptString) {
	s.GatewayID = val
}

// Ref: #/components/schemas/PaymentStatus
type PaymentStatus string

const (
	PaymentStatusPending           PaymentStatus = "pending"
	PaymentStatusWaitingForCapture PaymentStatus = "waiting_for_capture"
	PaymentStatusSucceeded         PaymentStatus = "succeeded"
	PaymentStatusCanceled          PaymentStatus = "canceled"
)

// AllValues returns all PaymentStatus values.
func (PaymentStatus) AllValues() []PaymentStatus {
	return []PaymentStatus{
		PaymentStatusPending,
		PaymentStatusWaitingForCapture,
		PaymentStatusSucceeded,
		PaymentStatusCanceled,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PaymentStatus) MarshalText() ([]byte, error) {
	switch s {
	case PaymentStatusPending:
		return []byte(s), nil
	case PaymentStatusWaitingForCapture:
		return []byte(s), nil
	case PaymentStatusSucceeded:
		return []byte(s), nil
	case PaymentStatusCanceled:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PaymentStatus) UnmarshalText(data []byte) error {
	switch PaymentStatus(data) {
	case PaymentStatusPending:
		*s = PaymentStatusPending
		return nil
	case PaymentStatusWaitingForCapture:
		*s = PaymentStatusWaitingForCapture
		return nil
	case PaymentStatusSucceeded:
		*s = PaymentStatusSucceeded
		return nil
	case PaymentStatusCanceled:
		*s = PaymentStatusCanceled
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/RefundPayment
type RefundPayment struct {
	ID        string        `json:"id"`
	PaymentID string        `json:"payment_id"`
	Status    PaymentStatus `json:"status"`
	CreatedAt time.Time     `json:"created_at"`
	Amount    Amount        `json:"amount"`
}

// GetID returns the value of ID.
func (s *RefundPayment) GetID() string {
	return s.ID
}

// GetPaymentID returns the value of PaymentID.
func (s *RefundPayment) GetPaymentID() string {
	return s.PaymentID
}

// GetStatus returns the value of Status.
func (s *RefundPayment) GetStatus() PaymentStatus {
	return s.Status
}

// GetCreatedAt returns the value of CreatedAt.
func (s *RefundPayment) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetAmount returns the value of Amount.
func (s *RefundPayment) GetAmount() Amount {
	return s.Amount
}

// SetID sets the value of ID.
func (s *RefundPayment) SetID(val string) {
	s.ID = val
}

// SetPaymentID sets the value of PaymentID.
func (s *RefundPayment) SetPaymentID(val string) {
	s.PaymentID = val
}

// SetStatus sets the value of Status.
func (s *RefundPayment) SetStatus(val PaymentStatus) {
	s.Status = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *RefundPayment) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetAmount sets the value of Amount.
func (s *RefundPayment) SetAmount(val Amount) {
	s.Amount = val
}

// Ref: #/components/schemas/ReqPayment
type ReqPayment struct {
	Amount       Amount                    `json:"amount"`
	Confirmation OptReqPaymentConfirmation `json:"confirmation"`
	// Автоматический прием  поступившего платежа.
	Capture OptBool `json:"capture"`
	// Описание транзакции (не более 128 символов), которое вы
	// увидите в личном кабинете ЮKassa, а пользователь — при
	// оплате. Например: «Оплата заказа № 72 для user@yoomoney.ru».
	Description OptString `json:"description"`
	// Сохранение платежных данных (с их помощью можно
	// проводить повторные безакцептные списания ).
	// Значение true инициирует создание многоразового
	// payment_method.
	SavePaymentMethod OptBool `json:"save_payment_method"`
	// Идентификатор сохраненного способа оплаты.
	PaymentMethodID OptString   `json:"payment_method_id"`
	Metadata        OptMetadata `json:"metadata"`
}

// GetAmount returns the value of Amount.
func (s *ReqPayment) GetAmount() Amount {
	return s.Amount
}

// GetConfirmation returns the value of Confirmation.
func (s *ReqPayment) GetConfirmation() OptReqPaymentConfirmation {
	return s.Confirmation
}

// GetCapture returns the value of Capture.
func (s *ReqPayment) GetCapture() OptBool {
	return s.Capture
}

// GetDescription returns the value of Description.
func (s *ReqPayment) GetDescription() OptString {
	return s.Description
}

// GetSavePaymentMethod returns the value of SavePaymentMethod.
func (s *ReqPayment) GetSavePaymentMethod() OptBool {
	return s.SavePaymentMethod
}

// GetPaymentMethodID returns the value of PaymentMethodID.
func (s *ReqPayment) GetPaymentMethodID() OptString {
	return s.PaymentMethodID
}

// GetMetadata returns the value of Metadata.
func (s *ReqPayment) GetMetadata() OptMetadata {
	return s.Metadata
}

// SetAmount sets the value of Amount.
func (s *ReqPayment) SetAmount(val Amount) {
	s.Amount = val
}

// SetConfirmation sets the value of Confirmation.
func (s *ReqPayment) SetConfirmation(val OptReqPaymentConfirmation) {
	s.Confirmation = val
}

// SetCapture sets the value of Capture.
func (s *ReqPayment) SetCapture(val OptBool) {
	s.Capture = val
}

// SetDescription sets the value of Description.
func (s *ReqPayment) SetDescription(val OptString) {
	s.Description = val
}

// SetSavePaymentMethod sets the value of SavePaymentMethod.
func (s *ReqPayment) SetSavePaymentMethod(val OptBool) {
	s.SavePaymentMethod = val
}

// SetPaymentMethodID sets the value of PaymentMethodID.
func (s *ReqPayment) SetPaymentMethodID(val OptString) {
	s.PaymentMethodID = val
}

// SetMetadata sets the value of Metadata.
func (s *ReqPayment) SetMetadata(val OptMetadata) {
	s.Metadata = val
}

// ReqPaymentConfirmation represents sum type.
type ReqPaymentConfirmation struct {
	Type                        ReqPaymentConfirmationType // switch on this field
	PaymentConfirmationEmbedded PaymentConfirmationEmbedded
}

// ReqPaymentConfirmationType is oneOf type of ReqPaymentConfirmation.
type ReqPaymentConfirmationType string

// Possible values for ReqPaymentConfirmationType.
const (
	PaymentConfirmationEmbeddedReqPaymentConfirmation ReqPaymentConfirmationType = "PaymentConfirmationEmbedded"
)

// IsPaymentConfirmationEmbedded reports whether ReqPaymentConfirmation is PaymentConfirmationEmbedded.
func (s ReqPaymentConfirmation) IsPaymentConfirmationEmbedded() bool {
	return s.Type == PaymentConfirmationEmbeddedReqPaymentConfirmation
}

// SetPaymentConfirmationEmbedded sets ReqPaymentConfirmation to PaymentConfirmationEmbedded.
func (s *ReqPaymentConfirmation) SetPaymentConfirmationEmbedded(v PaymentConfirmationEmbedded) {
	s.Type = PaymentConfirmationEmbeddedReqPaymentConfirmation
	s.PaymentConfirmationEmbedded = v
}

// GetPaymentConfirmationEmbedded returns PaymentConfirmationEmbedded and true boolean if ReqPaymentConfirmation is PaymentConfirmationEmbedded.
func (s ReqPaymentConfirmation) GetPaymentConfirmationEmbedded() (v PaymentConfirmationEmbedded, ok bool) {
	if !s.IsPaymentConfirmationEmbedded() {
		return v, false
	}
	return s.PaymentConfirmationEmbedded, true
}

// NewPaymentConfirmationEmbeddedReqPaymentConfirmation returns new ReqPaymentConfirmation from PaymentConfirmationEmbedded.
func NewPaymentConfirmationEmbeddedReqPaymentConfirmation(v PaymentConfirmationEmbedded) ReqPaymentConfirmation {
	var s ReqPaymentConfirmation
	s.SetPaymentConfirmationEmbedded(v)
	return s
}

// Ref: #/components/schemas/ReqRefundPayment
type ReqRefundPayment struct {
	Amount    Amount `json:"amount"`
	PaymentID string `json:"payment_id"`
}

// GetAmount returns the value of Amount.
func (s *ReqRefundPayment) GetAmount() Amount {
	return s.Amount
}

// GetPaymentID returns the value of PaymentID.
func (s *ReqRefundPayment) GetPaymentID() string {
	return s.PaymentID
}

// SetAmount sets the value of Amount.
func (s *ReqRefundPayment) SetAmount(val Amount) {
	s.Amount = val
}

// SetPaymentID sets the value of PaymentID.
func (s *ReqRefundPayment) SetPaymentID(val string) {
	s.PaymentID = val
}

type V3PaymentsGetOK struct {
	Limit      OptInt    `json:"limit"`
	NextCursor OptString `json:"next_cursor"`
	Type       OptString `json:"type"`
	Items      []Payment `json:"items"`
}

// GetLimit returns the value of Limit.
func (s *V3PaymentsGetOK) GetLimit() OptInt {
	return s.Limit
}

// GetNextCursor returns the value of NextCursor.
func (s *V3PaymentsGetOK) GetNextCursor() OptString {
	return s.NextCursor
}

// GetType returns the value of Type.
func (s *V3PaymentsGetOK) GetType() OptString {
	return s.Type
}

// GetItems returns the value of Items.
func (s *V3PaymentsGetOK) GetItems() []Payment {
	return s.Items
}

// SetLimit sets the value of Limit.
func (s *V3PaymentsGetOK) SetLimit(val OptInt) {
	s.Limit = val
}

// SetNextCursor sets the value of NextCursor.
func (s *V3PaymentsGetOK) SetNextCursor(val OptString) {
	s.NextCursor = val
}

// SetType sets the value of Type.
func (s *V3PaymentsGetOK) SetType(val OptString) {
	s.Type = val
}

// SetItems sets the value of Items.
func (s *V3PaymentsGetOK) SetItems(val []Payment) {
	s.Items = val
}

// YookassaHookPostOK is response for YookassaHookPost operation.
type YookassaHookPostOK struct{}

type YookassaHookPostReq struct {
	Type   YookassaHookPostReqType   `json:"type"`
	Event  YookassaHookPostReqEvent  `json:"event"`
	Object YookassaHookPostReqObject `json:"object"`
}

// GetType returns the value of Type.
func (s *YookassaHookPostReq) GetType() YookassaHookPostReqType {
	return s.Type
}

// GetEvent returns the value of Event.
func (s *YookassaHookPostReq) GetEvent() YookassaHookPostReqEvent {
	return s.Event
}

// GetObject returns the value of Object.
func (s *YookassaHookPostReq) GetObject() YookassaHookPostReqObject {
	return s.Object
}

// SetType sets the value of Type.
func (s *YookassaHookPostReq) SetType(val YookassaHookPostReqType) {
	s.Type = val
}

// SetEvent sets the value of Event.
func (s *YookassaHookPostReq) SetEvent(val YookassaHookPostReqEvent) {
	s.Event = val
}

// SetObject sets the value of Object.
func (s *YookassaHookPostReq) SetObject(val YookassaHookPostReqObject) {
	s.Object = val
}

type YookassaHookPostReqEvent string

const (
	YookassaHookPostReqEventPaymentWaitingForCapture YookassaHookPostReqEvent = "payment.waiting_for_capture"
	YookassaHookPostReqEventPaymentSucceeded         YookassaHookPostReqEvent = "payment.succeeded"
	YookassaHookPostReqEventPaymentCanceled          YookassaHookPostReqEvent = "payment.canceled"
	YookassaHookPostReqEventRefundSucceeded          YookassaHookPostReqEvent = "refund.succeeded"
	YookassaHookPostReqEventPayoutSucceeded          YookassaHookPostReqEvent = "payout.succeeded"
	YookassaHookPostReqEventPayoutCanceled           YookassaHookPostReqEvent = "payout.canceled"
	YookassaHookPostReqEventDealClosed               YookassaHookPostReqEvent = "deal.closed"
)

// AllValues returns all YookassaHookPostReqEvent values.
func (YookassaHookPostReqEvent) AllValues() []YookassaHookPostReqEvent {
	return []YookassaHookPostReqEvent{
		YookassaHookPostReqEventPaymentWaitingForCapture,
		YookassaHookPostReqEventPaymentSucceeded,
		YookassaHookPostReqEventPaymentCanceled,
		YookassaHookPostReqEventRefundSucceeded,
		YookassaHookPostReqEventPayoutSucceeded,
		YookassaHookPostReqEventPayoutCanceled,
		YookassaHookPostReqEventDealClosed,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s YookassaHookPostReqEvent) MarshalText() ([]byte, error) {
	switch s {
	case YookassaHookPostReqEventPaymentWaitingForCapture:
		return []byte(s), nil
	case YookassaHookPostReqEventPaymentSucceeded:
		return []byte(s), nil
	case YookassaHookPostReqEventPaymentCanceled:
		return []byte(s), nil
	case YookassaHookPostReqEventRefundSucceeded:
		return []byte(s), nil
	case YookassaHookPostReqEventPayoutSucceeded:
		return []byte(s), nil
	case YookassaHookPostReqEventPayoutCanceled:
		return []byte(s), nil
	case YookassaHookPostReqEventDealClosed:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *YookassaHookPostReqEvent) UnmarshalText(data []byte) error {
	switch YookassaHookPostReqEvent(data) {
	case YookassaHookPostReqEventPaymentWaitingForCapture:
		*s = YookassaHookPostReqEventPaymentWaitingForCapture
		return nil
	case YookassaHookPostReqEventPaymentSucceeded:
		*s = YookassaHookPostReqEventPaymentSucceeded
		return nil
	case YookassaHookPostReqEventPaymentCanceled:
		*s = YookassaHookPostReqEventPaymentCanceled
		return nil
	case YookassaHookPostReqEventRefundSucceeded:
		*s = YookassaHookPostReqEventRefundSucceeded
		return nil
	case YookassaHookPostReqEventPayoutSucceeded:
		*s = YookassaHookPostReqEventPayoutSucceeded
		return nil
	case YookassaHookPostReqEventPayoutCanceled:
		*s = YookassaHookPostReqEventPayoutCanceled
		return nil
	case YookassaHookPostReqEventDealClosed:
		*s = YookassaHookPostReqEventDealClosed
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// YookassaHookPostReqObject represents sum type.
type YookassaHookPostReqObject struct {
	Type          YookassaHookPostReqObjectType // switch on this field
	RefundPayment RefundPayment
	Payment       Payment
}

// YookassaHookPostReqObjectType is oneOf type of YookassaHookPostReqObject.
type YookassaHookPostReqObjectType string

// Possible values for YookassaHookPostReqObjectType.
const (
	RefundPaymentYookassaHookPostReqObject YookassaHookPostReqObjectType = "RefundPayment"
	PaymentYookassaHookPostReqObject       YookassaHookPostReqObjectType = "Payment"
)

// IsRefundPayment reports whether YookassaHookPostReqObject is RefundPayment.
func (s YookassaHookPostReqObject) IsRefundPayment() bool {
	return s.Type == RefundPaymentYookassaHookPostReqObject
}

// IsPayment reports whether YookassaHookPostReqObject is Payment.
func (s YookassaHookPostReqObject) IsPayment() bool {
	return s.Type == PaymentYookassaHookPostReqObject
}

// SetRefundPayment sets YookassaHookPostReqObject to RefundPayment.
func (s *YookassaHookPostReqObject) SetRefundPayment(v RefundPayment) {
	s.Type = RefundPaymentYookassaHookPostReqObject
	s.RefundPayment = v
}

// GetRefundPayment returns RefundPayment and true boolean if YookassaHookPostReqObject is RefundPayment.
func (s YookassaHookPostReqObject) GetRefundPayment() (v RefundPayment, ok bool) {
	if !s.IsRefundPayment() {
		return v, false
	}
	return s.RefundPayment, true
}

// NewRefundPaymentYookassaHookPostReqObject returns new YookassaHookPostReqObject from RefundPayment.
func NewRefundPaymentYookassaHookPostReqObject(v RefundPayment) YookassaHookPostReqObject {
	var s YookassaHookPostReqObject
	s.SetRefundPayment(v)
	return s
}

// SetPayment sets YookassaHookPostReqObject to Payment.
func (s *YookassaHookPostReqObject) SetPayment(v Payment) {
	s.Type = PaymentYookassaHookPostReqObject
	s.Payment = v
}

// GetPayment returns Payment and true boolean if YookassaHookPostReqObject is Payment.
func (s YookassaHookPostReqObject) GetPayment() (v Payment, ok bool) {
	if !s.IsPayment() {
		return v, false
	}
	return s.Payment, true
}

// NewPaymentYookassaHookPostReqObject returns new YookassaHookPostReqObject from Payment.
func NewPaymentYookassaHookPostReqObject(v Payment) YookassaHookPostReqObject {
	var s YookassaHookPostReqObject
	s.SetPayment(v)
	return s
}

type YookassaHookPostReqType string

const (
	YookassaHookPostReqTypeNotification YookassaHookPostReqType = "notification"
)

// AllValues returns all YookassaHookPostReqType values.
func (YookassaHookPostReqType) AllValues() []YookassaHookPostReqType {
	return []YookassaHookPostReqType{
		YookassaHookPostReqTypeNotification,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s YookassaHookPostReqType) MarshalText() ([]byte, error) {
	switch s {
	case YookassaHookPostReqTypeNotification:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *YookassaHookPostReqType) UnmarshalText(data []byte) error {
	switch YookassaHookPostReqType(data) {
	case YookassaHookPostReqTypeNotification:
		*s = YookassaHookPostReqTypeNotification
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
