// Code generated by ogen, DO NOT EDIT.

package ogencl

// OperationName is the ogen operation name
type OperationName = string

const (
	V3PaymentsGetOperation          OperationName = "V3PaymentsGet"
	V3PaymentsPaymentIDGetOperation OperationName = "V3PaymentsPaymentIDGet"
	V3PaymentsPostOperation         OperationName = "V3PaymentsPost"
	V3RefundsPostOperation          OperationName = "V3RefundsPost"
	YookassaHookPostOperation       OperationName = "YookassaHookPost"
)
