// Code generated by ogen, DO NOT EDIT.

package ogencl

import (
	"net/http"
)

func encodeYookassaHookPostResponse(response *YookassaHookPostOK, w http.ResponseWriter) error {
	w.WriteHeader(200)

	return nil
}
